# This is a basic workflow to help you get started with Actions

name: cacheStonks

# Controls when the workflow will run 4pm Mountain (+6hrs)
on:
  schedule:
  - cron: "0 20 * * 1-5" # Runs at 4pm every Monday, Wednesday, and Friday (Check https://crontab.guru/)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: REST API with curl1
        run: |
          curl -X GET "https://stock-scrape.herokuapp.com/api/stonks/?id=600&ticker=TSLA&type=stock&country=US&morningstar=t=0P0000OQN8"
